CC = g++
CFLAGS = -std=c++20 -Wall -pedantic
#SOURCES = main.cpp
SOURCES = main.cpp
CLASS = NDArray.h
CLASS_SOURCE = NDArray.cpp

ifeq ($(OS), Windows_NT)
	RM = del
	TARGET = main.exe
else
	RM = rm
	TARGET = main
endif

all:
	$(CC) $(CFLAGS) $(CLASS) -o $(TARGET) $(SOURCES)  $(CLASS_SOURCE)

clean:
	echo $(OS)
	$(RM) $(TARGET)

run: all
	$(TARGET)